### ISSUE TITLE
Pertinence de l'anglais par rapport au français ?

### ISSUE THREAD

**Issue by nicogodet** [rbignon/doctoshotgun#26]
Ce script est voué à être utilisé par une grande majorité d'utilisateur francophone.

Ne serait-il pas plus pertinent de le passer en français ?

cf. #25

**Comment by mirsella** [comment]
C'est un bon argument, mais la plupart d'entre nous pouvons facilement comprendre l'anglais surtout si on utilise GitHub un bot, alors que dans l'autre sens les Anglais ne comprennent surement pas le français.
L'anglais est compréhensible par nous, les Anglais ET le monde. C'est le langage international que tout le monde utilise sur GitHub.

Je suis d'accord qu'il faut donc faire attentions aux formulations des phrases, car elles peuvent avoir différentes significations selon les personnes et leurs anglais.

**Comment by nicogodet** [comment]
Je n'ai personnellement aucun problème avec l'anglais. Mais c'est suite à la PR 25 que je me suis posé cette question.

Cette issue avait pour but d'ouvrir le débat.

**Comment by Conobi** [comment]
Issue #43 shows that English is probably more accurate, since Doctolib is not only available in France. Maybe a solution would be to create a secondary Readme for bad English readers?
___
L'issue 43 montre vraiment que l'anglais est probablement plus pertinant, étant donné que Doctolib n'est visiblement pas seulement implanté en France. Après, rien n'empêcherait de créer un deuxième readme ou une doc en français pour les quelques personnes ayant du mal avec l'anglais?

**Comment by rbignon** [comment]
As now Doctoshotgun supports Germany, using English is definitely a good thing.
